routes/web.php
<?php

use App\Http\Controllers\Backend\DataPaketLatihanController;
use App\Http\Controllers\Backend\DataPelatihController;
use App\Http\Controllers\Backend\DataPengaduanController;
use App\Http\Controllers\Backend\PelangganController;
use App\Http\Controllers\Backend\TransaksiController;
use App\Http\Controllers\Frontend\AduanControllerr;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\DaftarController;
use App\Http\Controllers\Frontend\PelatihController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Models\DataPelatih;
use App\Models\DataPengaduan;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('frontend.dashboard');
})->name('homepage');

Route::group(['middleware' => ['role:admin', 'auth']], function () {

    // Dashboard
    Route::get('/dashboard', function () {
        $paket = PaketLatihan::count();
        $aduan = DataPengaduan::count();
        $transaksi = Transaksi::count();
        $pelatih = DataPelatih::count();
        $user = User::where('level', 'pelanggan')->count();
        return view('backend.dashboard', compact('paket', 'aduan', 'transaksi', 'user', 'pelatih'));
    })->name('dashboard');

    // Data Pelanggan
    Route::resource('pelanggan', PelangganController::class);

    // Data Pelatih
    Route::resource('dataPelatih', DataPelatihController::class);
    Route::get('/getDataPelatih', DataPelatihController::class . '@getDataPelatih');

    // Data Paket Latihan
    Route::resource('paket', DataPaketLatihanController::class);

    // Data Pengaduan
    Route::resource('pengaduan', DataPengaduanController::class);

    // Data Transaksi
    Route::resource('transaksi', TransaksiController::class);
    Route::get('/history', TransaksiController::class . '@history')->name('history.index');
});

Route::resource('daftar', DaftarController::class);
Route::resource('profile', ProfileController::class);
Route::resource('pelatih', PelatihController::class);

Route::get('/jadwal', DaftarController::class . '@getJadwal')->name('jadwal.index');

Route::get('/tutorial', function () {
    return view('frontend.pages.tutorial');
})->name('tutorial.index');

Route::group(['middleware' => ['role:user', 'auth']], function () {
    Route::resource('aduan', AduanControllerr::class);
    Route::get('/aduanSukses', AduanControllerr::class . '@aduanSuccess')->name('aduan.success');
    Route::get('/checkout/{id}', CheckoutController::class . '@checkout')->name('checkout');
    Route::post('/order', CheckoutController::class . '@store')->name('store.transaction');
    Route::get('/orderSukses', CheckoutController::class . '@orderSuccess')->name('order.success');
});


Route::get('/coba', function () {
    return PaketLatihan::with(['detail'])->where('id', 1)->where('status', 'aktif')->get();
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Frontend/AduanControllerr.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\DataPengaduan;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AduanControllerr extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('frontend.pages.pengaduan');
    }

    public function aduanSuccess()
    {
        return view('frontend.pages.aduanSukses');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'subjek' => 'required',
            'deskripsi' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        DataPengaduan::create([
            'user_id' => $request->input('user_id'),
            'subjek' => $request->input('subjek'),
            'deskripsi' => $request->input('deskripsi'),
        ]);

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CheckoutController extends Controller
{
    public function checkout(string $id)
    {
        $paket = PaketLatihan::with(['detail'])->where('id', $id)->where('status', 'aktif')->first();

        $user = User::with(['biodata'])->where('id', auth()->user()->id)->first();

        return view('frontend.pages.checkout', compact('paket', 'user'));
    }

    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'metode_pemb' => 'required|in:bank_bca,bank_bri,bank_bni',
            'bukti_bayar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'lap_lat' => 'required',
            'start' => 'required',
            'end' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $paket = PaketLatihan::where('id', $request->input('paket_id'))->first();
        $paket->update([
            'kuota' => $paket->kuota - 1,
        ]);

        if ($image = $request->file('bukti_bayar')) {

            $fileName = 'bukti-' . time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('uploads/img/', $fileName, 'public');

            // Store Data
            $transaksi = Transaksi::create([
                'metode_pemb' => $request->input('metode_pemb'),
                'user_id' => $request->input('user_id'),
                'paket_id' => $request->input('paket_id'),
                'bukti_bayar' => $fileName,
                'lap_lat' => $request->input('lap_lat'),
                'start' => $request->input('start'),
                'end' => $request->input('end'),
            ]);
        }

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Pesanan Anda Berhasil!',
        ]);
    }

    public function orderSuccess()
    {
        return view('frontend.pages.orderSukses');
    }
}

app/Http/Controllers/Frontend/DaftarController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use Illuminate\Http\Request;

class DaftarController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $paket = PaketLatihan::where('status', 'aktif')->get();
        $totalCoulumn = PaketLatihan::count();
        return view('frontend.pages.pendaftaran', compact('paket', 'totalCoulumn'));
    }

    public function homepage()
    {
        return view('frontend.dashboard');
    }

    public function getJadwal()
    {
        $event = array();
        $jadwal = Transaksi::with(['pelanggan', 'paket'])->where('status_pemb', 'pembayaran-valid')->get();
        foreach($jadwal as $item){
            $event[] = [
                'title' => $item->pelanggan->name,
                'start' => $item->start,
                'end' => $item->end
            ];
        }
        return view('frontend.pages.jadwal', compact('event'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $paket = PaketLatihan::with(['detail'])->where('id', $id)->where('status', 'aktif')->first();

        return view('frontend.pages.pendaftaran-detail', compact('paket'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/PelatihController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\DataPelatih;
use Illuminate\Http\Request;

class PelatihController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pelatih = DataPelatih::where('status', 'aktif')->get();
        return view('frontend.pages.pelatih', compact('pelatih'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user = User::with(['biodata'])->where('id', Auth::user()->id)->first();
        $dataOrder = Transaksi::where('user_id', Auth::user()->id)->get();

        return view('frontend.pages.profile', compact('user', 'dataOrder'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'nohp' => 'required',
            'umur' => 'required',
            'jk' => 'required',
            'alamat' => 'required',
            'status' => 'required',
            'pengalaman_tennis' => 'required',
        ]);

        $id = Auth::user()->id;

        $name = $request->input('name');
        $email = $request->input('email');
        $nohp = $request->input('nohp');

        $user = User::find($id);
        // Update Data Model User
        $user->update([
            'name' => $name,
            'email' => $email,
            'nohp' => $nohp,
        ]);

        $dataUser = Customer::where('user_id', $id)->first();
        $dataUser->update([
            'umur' => $request->input('umur'),
            'jenis_kelamin' => $request->input('jk'),
            'alamat' => $request->input('alamat'),
            'status' => $request->input('status'),
            'pengalaman_tennis' => $request->input('pengalaman_tennis'),
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $id = Auth::user()->id;
        $name = $request->input('name');
        $email = $request->input('email');
        $nohp = $request->input('nohp');

        $user = User::find($id);
        // Update Data Model User
        $user->update([
            'name' => $name,
            'email' => $email,
            'nohp' => $nohp,
        ]);

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/frontend/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <link rel="icon" type="image/x-icon" href="images/favicon.ico" />
    <title>Tennis Club</title>

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic"
        type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700" type="text/css">
    <link rel="stylesheet" href="{{ asset('frontend/css/fontello/css/fontello.min.css') }}" type="text/css"
        media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/js/vendor/revslider/css/settings.min.css') }}" type="text/css"
        media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/woocommerce/woocommerce-layout.css') }}" type="text/css"
        media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/css/woocommerce/woocommerce-smallscreen.css') }}" type="text/css"
        media="only screen and (max-width: 768px)" />
    <link rel="stylesheet" href="{{ asset('frontend/css/woocommerce/woocommerce.css') }}" type="text/css"
        media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/wp-cloudy/wpcloudy.min.css') }}" type="text/css"
        media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/css/wp-cloudy/wpcloudy-anim.min.css') }}" type="text/css"
        media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/style.min.css') }}" type="text/css" media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/css/core.animation.min.css') }}" type="text/css" media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/css/shortcodes.min.css') }}" type="text/css" media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/plugin.woocommerce.min.css') }}" type="text/css"
        media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/skin.min.css') }}" type="text/css" media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/css/responsive.min.css') }}" type="text/css" media="all" />

    <link rel="stylesheet" href="{{ asset('frontend/js/core.messages/core.messages.min.css') }}" type="text/css"
        media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/js/magnific/magnific-popup.min.css') }}" type="text/css"
        media="all" />
    @stack('style-alt')
    <link rel="stylesheet" href="{{ asset('frontend/css/core.portfolio.min.css') }}" type="text/css" media="all" />
    <link rel="stylesheet" href="{{ asset('frontend/js/swiper/swiper.min.css') }}" type="text/css" media="all" />
</head>

<body
    class="home page tennisclub_body body_style_wide body_filled article_style_stretch top_panel_show top_panel_above sidebar_hide">
    <div class="body_wrap">
        <div class="page_wrap">
            @include('frontend.layouts.navbar')
            <!-- Page Content Wrap -->
            @yield('content')
            <!-- /Page Content Wrap -->
            <!-- Copyright -->
            <div class="copyright_wrap copyright_style_menu">
                <div class="copyright_wrap_inner">
                    <div class="content_wrap">
                        <div class="copyright_text">ThemeREX © 2016 All Rights Reserved
                            <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Copyright -->
        </div>
    </div>
    <!-- Side block with weather plugin -->
    <a href="#" class="scroll_to_top icon-up" title="Scroll to top"></a>

    <script type="text/javascript" src="{{ asset('frontend/js/jquery/jquery.js') }}"></script>

    <script type="text/javascript" src="{{ asset('frontend/js/_packed.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/global.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('frontend/js/vendor/revslider/jquery.themepunch.tools.min.js') }}">
    </script>
    <script type="text/javascript" src="{{ asset('frontend/js/vendor/revslider/jquery.themepunch.revolution.min.js') }}">
    </script>
    <script type="text/javascript"
        src="{{ asset('frontend/js/vendor/revslider/extensions/revolution.extension.slideanims.min.js') }}"></script>
    <script type="text/javascript"
        src="{{ asset('frontend/js/vendor/revslider/extensions/revolution.extension.layeranimation.min.js') }}"></script>
    <script type="text/javascript"
        src="{{ asset('frontend/js/vendor/revslider/extensions/revolution.extension.navigation.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('frontend/js/vendor/woocommerce/woocommerce.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/vendor/woocommerce/cart-fragments.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('frontend/js/core.utils.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/core.init.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/theme.init.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/shortcodes.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('frontend/js/core.messages/core.messages.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('frontend/js/swiper/swiper.min.js') }}"></script>

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?key="></script>
    <script type="text/javascript" src="{{ asset('frontend/js/core.googlemap.min.js') }}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @stack('script-alt')
</body>

</html>

resources/views/frontend/layouts/navbar.blade.php
<!-- Header -->
<header class="top_panel_wrap top_panel_style_3 scheme_original">
    <div class="top_panel_wrap_inner top_panel_inner_style_3 top_panel_position_above">
        <!-- User panel -->
        <div class="top_panel_top">
            <div class="content_wrap clearfix">
                <div class="top_panel_top_contact_area icon-smartphone">+44 (0) 1234 56789</div>
                <div class="top_panel_top_open_hours icon-mail-2">info@sitename.com</div>
                <div class="top_panel_top_user_area">
                    <ul id="menu_user" class="menu_user_nav">
                        @if (Auth::check())
                            <li class="menu_user_register">
                                <a href="{{ route('profile.index') }}"
                                    class="popup_link popup_register_link icon-user">Profil</a>
                            </li>
                        @else
                            <li class="menu_user_register">
                                <a href="{{ route('register') }}"
                                    class="popup_link popup_register_link icon-pencil">Register</a>
                            </li>
                            <li class="menu_user_login">
                                <a href="{{ route('login') }}" class="popup_link popup_login_link icon-user">Login</a>
                            </li>
                        @endif
                        <li class="top_panel_link">
                            <a href="{{ route('daftar.index') }}">Beli Paket Latihan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /User panel -->
        <!-- Top Menu -->
        <div class="top_panel_middle">
            <div class="content_wrap">
                <div class="contact_logo">
                    <div class="logo">
                        <a href="index.html">
                            <img src="http://placehold.it/290x50" class="logo_main" alt="">
                            <img src="http://placehold.it/290x50" class="logo_fixed" alt=""></a>
                    </div>
                </div>
                <div class="menu_main_social_wrap">
                    {{-- <div class="top_panel_top_socials">
                        <div class="sc_socials sc_socials_type_icons sc_socials_shape_square sc_socials_size_small">
                            <div class="sc_socials_item">
                                <a href="#" target="_blank" class="social_icons social_twitter">
                                    <span class="icon-twitter"></span>
                                </a>
                            </div>
                            <div class="sc_socials_item">
                                <a href="#" target="_blank" class="social_icons social_facebook">
                                    <span class="icon-facebook"></span>
                                </a>
                            </div>
                            <div class="sc_socials_item">
                                <a href="#" target="_blank" class="social_icons social_gplus">
                                    <span class="icon-gplus"></span>
                                </a>
                            </div>
                        </div>
                    </div> --}}
                    <div class="menu_main_wrap">
                        <a href="#" class="menu_main_responsive_button icon-menu"></a>
                        <nav class="menu_main_nav_area">
                            <ul id="menu_main" class="menu_main_nav">
                                <li class="menu-item current-menu-item current_page_item">
                                    <a href="{{ route('homepage') }}">Home</a>
                                </li>
                                <li class="menu-item">
                                    <a href="{{ route('tutorial.index') }}">Tutorial</a>
                                </li>
                                <li class="menu-item">
                                    <a href="{{ route('jadwal.index') }}">Jadwal Kegiatan</a>
                                </li>
                                <li class="menu-item"
                                    class="{{ request()->segment(1) == 'daftar' ? 'current-menu-item current_page_item' : '' }}">
                                    <a href="{{ route('daftar.index') }}">Pendaftaran</a>
                                </li>
                                @if (Auth::check())
                                    <li class="menu-item"
                                        class="{{ request()->segment(1) == 'aduan' ? 'current-menu-item current_page_item' : '' }}">
                                        <a href="{{ route('aduan.index') }}">Pengaduan</a>
                                    </li>
                                @endif
                                <li class="menu-item">
                                    <a href="{{ route('pelatih.index') }}">Profil Pelatih</a>
                                </li>
                                @if (Auth::check())
                                    <li class="menu-item">
                                        <form method="POST" action="{{ route('logout') }}">
                                            @csrf
                                            <button class="">
                                                <i class="fa fa-ban fa-fw pull-right"></i> Logout
                                            </button>
                                        </form>
                                    </li>
                                @endif
                                {{-- <li class="menu-item menu-item-has-children">
                                    <a href="#">Profil</a>
                                    <ul class="sub-menu">
                                        <li class="menu-item">
                                            <a href="typography.html">Pelatih</a>
                                        </li>
                                        <li class="menu-item">
                                            <a href="shortcodes.html">User</a>
                                        </li>
                                    </ul>
                                </li> --}}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Top Menu -->
    </div>
</header>
<!-- /Header -->
<!-- Header Mobile -->
<div class="header_mobile">
    <div class="content_wrap">
        <div class="menu_button icon-menu"></div>
        <div class="logo">
            <a href="index.html">
                <img src="http://placehold.it/290x50" class="logo_main" alt="">
            </a>
        </div>
    </div>
    <div class="side_wrap">
        <div class="close">Close</div>
        <div class="panel_top">
            <nav class="menu_main_nav_area">
                <ul id="menu_main_mobile" class="menu_main_nav">
                    <li class="menu-item current-menu-item current_page_item">
                        <a href="{{ route('homepage') }}">Home</a>
                    </li>
                    <li class="menu-item">
                        <a href="{{ route('tutorial.index') }}">Tutorial</a>
                    </li>
                    <li class="menu-item">
                        <a href="{{ route('jadwal.index') }}">Jadwal Kegiatan</a>
                    </li>
                    <li class="menu-item"
                        class="{{ request()->segment(1) == 'daftar' ? 'current-menu-item current_page_item' : '' }}">
                        <a href="{{ route('daftar.index') }}">Pendaftaran</a>
                    </li>
                    <li class="menu-item"
                        class="{{ request()->segment(1) == 'aduan' ? 'current-menu-item current_page_item' : '' }}">
                        <a href="{{ route('aduan.index') }}">Pengaduan</a>
                    </li>
                    <li class="menu-item">
                        <a href="#">Profil Pelatih</a>
                    </li>
                </ul>
            </nav>
            <div class="search_wrap search_style_regular search_state_fixed">
                <div class="search_form_wrap">
                    <form method="get" class="search_form" action="#">
                        <button type="submit" class="search_submit icon-magnifier" title="Start search"></button>
                        <input type="text" class="search_field" placeholder="Search" value="" name="s" />
                    </form>
                </div>
                <div class="search_results widget_area scheme_original">
                    <a class="search_results_close icon-cancel"></a>
                    <div class="search_results_content"></div>
                </div>
            </div>
            @if (Auth::check())
                <div class="login">
                    <a href="{{ route('profile.index') }}" class="popup_link popup_login_link">Profile</a>
                </div>
            @else
                <div class="login">
                    <a href="{{ route('login') }}" class="popup_link popup_login_link">Login</a>
                </div>
                <div class="login">
                    <a href="{{ route('register') }}" class="popup_link popup_login_link">Register</a>
                </div>
            @endif
        </div>
        <div class="panel_bottom">
            <div class="contact_socials">
                <div class="sc_socials sc_socials_type_icons sc_socials_shape_square sc_socials_size_small">
                    <div class="sc_socials_item">
                        <a href="#" target="_blank" class="social_icons social_twitter">
                            <span class="icon-twitter"></span>
                        </a>
                    </div>
                    <div class="sc_socials_item">
                        <a href="#" target="_blank" class="social_icons social_facebook">
                            <span class="icon-facebook"></span>
                        </a>
                    </div>
                    <div class="sc_socials_item">
                        <a href="#" target="_blank" class="social_icons social_gplus">
                            <span class="icon-gplus"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="top_panel_link">
            <a href="{{ route('daftar.index') }}">Beli Paket Latihan</a>
        </div>
    </div>
    <div class="mask"></div>
</div>
<!-- /Header Mobile -->