routes/web.php
<?php

use App\Http\Controllers\Backend\DataPaketLatihanController;
use App\Http\Controllers\Backend\DataPelatihController;
use App\Http\Controllers\Backend\DataPengaduanController;
use App\Http\Controllers\Backend\PelangganController;
use App\Http\Controllers\Backend\TransaksiController;
use App\Http\Controllers\Frontend\AduanControllerr;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\DaftarController;
use App\Http\Controllers\Frontend\PelatihController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Models\DataPelatih;
use App\Models\DataPengaduan;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('frontend.dashboard');
})->name('homepage');

Route::group(['middleware' => ['role:admin', 'auth']], function () {

    // Dashboard
    Route::get('/dashboard', function () {
        $paket = PaketLatihan::count();
        $aduan = DataPengaduan::count();
        $transaksi = Transaksi::count();
        $pelatih = DataPelatih::count();
        $user = User::where('level', 'pelanggan')->count();
        return view('backend.dashboard', compact('paket', 'aduan', 'transaksi', 'user', 'pelatih'));
    })->name('dashboard');

    // Data Pelanggan
    Route::resource('pelanggan', PelangganController::class);

    // Data Pelatih
    Route::resource('dataPelatih', DataPelatihController::class);
    Route::get('/getDataPelatih', DataPelatihController::class . '@getDataPelatih');

    // Data Paket Latihan
    Route::resource('paket', DataPaketLatihanController::class);

    // Data Pengaduan
    Route::resource('pengaduan', DataPengaduanController::class);

    // Data Transaksi
    Route::resource('transaksi', TransaksiController::class);
    Route::get('/history', TransaksiController::class . '@history')->name('history.index');
});

Route::resource('daftar', DaftarController::class);
Route::resource('profile', ProfileController::class);
Route::resource('pelatih', PelatihController::class);

Route::get('/jadwal', DaftarController::class . '@getJadwal')->name('jadwal.index');

Route::get('/tutorial', function () {
    return view('frontend.pages.tutorial');
})->name('tutorial.index');

Route::group(['middleware' => ['role:user', 'auth']], function () {
    Route::resource('aduan', AduanControllerr::class);
    Route::get('/aduanSukses', AduanControllerr::class . '@aduanSuccess')->name('aduan.success');
    Route::get('/checkout/{id}', CheckoutController::class . '@checkout')->name('checkout');
    Route::post('/order', CheckoutController::class . '@store')->name('store.transaction');
    Route::get('/orderSukses', CheckoutController::class . '@orderSuccess')->name('order.success');
});


Route::get('/coba', function () {
    return PaketLatihan::with(['detail'])->where('id', 1)->where('status', 'aktif')->get();
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Frontend/AduanControllerr.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\DataPengaduan;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AduanControllerr extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('frontend.pages.pengaduan');
    }

    public function aduanSuccess()
    {
        return view('frontend.pages.aduanSukses');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'subjek' => 'required',
            'deskripsi' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        DataPengaduan::create([
            'user_id' => $request->input('user_id'),
            'subjek' => $request->input('subjek'),
            'deskripsi' => $request->input('deskripsi'),
        ]);

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CheckoutController extends Controller
{
    public function checkout(string $id)
    {
        $paket = PaketLatihan::with(['detail'])->where('id', $id)->where('status', 'aktif')->first();

        $user = User::with(['biodata'])->where('id', auth()->user()->id)->first();

        return view('frontend.pages.checkout', compact('paket', 'user'));
    }

    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'metode_pemb' => 'required|in:bank_bca,bank_bri,bank_bni',
            'bukti_bayar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'lap_lat' => 'required',
            'start' => 'required',
            'end' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $paket = PaketLatihan::where('id', $request->input('paket_id'))->first();
        $paket->update([
            'kuota' => $paket->kuota - 1,
        ]);

        if ($image = $request->file('bukti_bayar')) {

            $fileName = 'bukti-' . time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('uploads/img/', $fileName, 'public');

            // Store Data
            $transaksi = Transaksi::create([
                'metode_pemb' => $request->input('metode_pemb'),
                'user_id' => $request->input('user_id'),
                'paket_id' => $request->input('paket_id'),
                'bukti_bayar' => $fileName,
                'lap_lat' => $request->input('lap_lat'),
                'start' => $request->input('start'),
                'end' => $request->input('end'),
            ]);
        }

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Pesanan Anda Berhasil!',
        ]);
    }

    public function orderSuccess()
    {
        return view('frontend.pages.orderSukses');
    }
}

app/Http/Controllers/Frontend/DaftarController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use Illuminate\Http\Request;

class DaftarController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $paket = PaketLatihan::where('status', 'aktif')->get();
        $totalCoulumn = PaketLatihan::count();
        return view('frontend.pages.pendaftaran', compact('paket', 'totalCoulumn'));
    }

    public function homepage()
    {
        return view('frontend.dashboard');
    }

    public function getJadwal()
    {
        $event = array();
        $jadwal = Transaksi::with(['pelanggan', 'paket'])->where('status_pemb', 'pembayaran-valid')->get();
        foreach($jadwal as $item){
            $event[] = [
                'title' => $item->pelanggan->name,
                'start' => $item->start,
                'end' => $item->end
            ];
        }
        return view('frontend.pages.jadwal', compact('event'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $paket = PaketLatihan::with(['detail'])->where('id', $id)->where('status', 'aktif')->first();

        return view('frontend.pages.pendaftaran-detail', compact('paket'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/PelatihController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\DataPelatih;
use Illuminate\Http\Request;

class PelatihController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pelatih = DataPelatih::where('status', 'aktif')->get();
        return view('frontend.pages.pelatih', compact('pelatih'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Frontend/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user = User::with(['biodata'])->where('id', Auth::user()->id)->first();
        $dataOrder = Transaksi::where('user_id', Auth::user()->id)->get();

        return view('frontend.pages.profile', compact('user', 'dataOrder'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'nohp' => 'required',
            'umur' => 'required',
            'jk' => 'required',
            'alamat' => 'required',
            'status' => 'required',
            'pengalaman_tennis' => 'required',
        ]);

        $id = Auth::user()->id;

        $name = $request->input('name');
        $email = $request->input('email');
        $nohp = $request->input('nohp');

        $user = User::find($id);
        // Update Data Model User
        $user->update([
            'name' => $name,
            'email' => $email,
            'nohp' => $nohp,
        ]);

        $dataUser = Customer::where('user_id', $id)->first();
        $dataUser->update([
            'umur' => $request->input('umur'),
            'jenis_kelamin' => $request->input('jk'),
            'alamat' => $request->input('alamat'),
            'status' => $request->input('status'),
            'pengalaman_tennis' => $request->input('pengalaman_tennis'),
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $id = Auth::user()->id;
        $name = $request->input('name');
        $email = $request->input('email');
        $nohp = $request->input('nohp');

        $user = User::find($id);
        // Update Data Model User
        $user->update([
            'name' => $name,
            'email' => $email,
            'nohp' => $nohp,
        ]);

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/frontend/pages/aduanSukses.blade.php
@extends('frontend.layouts.main')

@section('content')
    <!-- Page Content Wrap -->
    <!-- Price Block -->
    <div class="page_content_wrap theme_background_1">
        <div class="content_wrap">
            <!-- Content -->
            <div class="content">
                <div class="post_item post_item_single page">
                    <section class="post_content">
                        <div class="padding_top_0_imp padding_bottom_7_857em_imp">
                            <div class="sc_content content_wrap">
                                <h3
                                    class="sc_title sc_title_underline sc_align_center text_align_center font_weight_600 font_size_3_571em">
                                    Aduan Anda Berhasil Terkirim!</h3>
                                <div class="text_uppercase margin_bottom_70_imp">
                                    <p class="price_blocks_subtitle text_align_center add_color_2 margin_auto">
                                       Mohon tunggu konfirmasi dari admin untuk melakukan tindak lanjut dari aduan yang anda kirimkan.
                                    </p>
                                </div>
                                <div class="row">
                                    <!-- /Price Block -->
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <!-- /Content -->
        </div>
    </div>
    <!-- Price Block -->
@endsection

resources/views/frontend/pages/jadwal.blade.php
@extends('frontend.layouts.main')

<script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.4/index.global.min.js'></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {

        var calendarEl = document.getElementById('calendar');
        var events = @json($event);

        var calendar = new FullCalendar.Calendar(calendarEl, {
            schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
            themeSystem: 'bootstrap5',
            initialView: 'timeGridWeek',
            events: events
        });
        calendar.render();


    });
</script>

<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'>
<link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'>

@section('content')
    <!-- Page Content Wrap -->
    <!-- Price Block -->
    <div class="page_content_wrap theme_background_1">
        <div class="content_wrap">
            <!-- Content -->
            <div class="content">
                <div class="post_item post_item_single page">
                    <section class="post_content">
                        <div class="padding_top_0_imp padding_bottom_7_857em_imp">
                            <div class="sc_content content_wrap">
                                <h3
                                    class="sc_title sc_title_underline sc_align_center text_align_center font_weight_600 font_size_3_571em">
                                    Choose your Package</h3>
                                <div class="text_uppercase margin_bottom_70_imp">
                                    <p class="price_blocks_subtitle text_align_center add_color_2 margin_auto">
                                        Tennis Club is honored to work with the country’s league best tennis
                                        players that now can become your personal coach and help you win
                                    </p>
                                </div>
                                <div class="row">
                                    <div class="card">
                                        <div class="card-body">
                                            <div id='calendar'></div>
                                        </div>
                                    </div>
                                    <!-- /Price Block -->
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <!-- /Content -->
        </div>
    </div>
    <!-- Price Block -->
@endsection

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
</script>

resources/views/frontend/pages/pendaftaran.blade.php
@extends('frontend.layouts.main')


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

@section('content')
    <!-- Page Content Wrap -->
    <!-- Price Block -->
    <div class="page_content_wrap theme_background_1">
        <div class="content_wrap">
            <!-- Content -->
            <div class="content">
                <div class="post_item post_item_single page">
                    <section class="post_content">
                        <div class="padding_top_0_imp padding_bottom_7_857em_imp">
                            <div class="sc_content content_wrap">
                                <h3
                                    class="sc_title sc_title_underline sc_align_center text_align_center font_weight_600 font_size_3_571em">
                                    Choose your Package</h3>
                                <div class="text_uppercase margin_bottom_70_imp">
                                    <p class="price_blocks_subtitle text_align_center add_color_2 margin_auto">
                                        Tennis Club is honored to work with the country’s league best tennis
                                        players that now can become your personal coach and help you win
                                    </p>
                                </div>
                                <div class="row">

                                    @foreach ($paket as $item)
                                        <!-- Price Block -->
                                        <div class="col-md-4 mb-4">
                                            <div class="sc_price_block sc_price_block_style_2">
                                                <div class="sc_price_block_title">
                                                    <span>{{ ucfirst($item->nama_paket) }}</span>
                                                </div>
                                                <div class="sc_price_block_money">
                                                    <div class="sc_price">
                                                        <span class="sc_price_currency">Rp.</span>
                                                        <span
                                                            class="sc_price_money">{{ number_format($item->harga) }}</span>
                                                        <span class="sc_price_period">mg</span>
                                                    </div>
                                                </div>
                                                <div class="sc_price_block_description" style="margin-top: -20px">
                                                    {{-- Jumlah Pelatih {{ $item->jml_pelatih }},<br>
                                                    Jumlah Asisten {{ $item->jml_asisten }},<br>
                                                    Jumlah BallBoy {{ $item->jml_ballboy }}, <br> --}}
                                                    {{ date('d F Y', strtotime($item->tgl_start)) }} -
                                                    {{ date('d F Y', strtotime($item->tgl_end)) }} <br>

                                                    {{ date('h:i:sa', strtotime($item->time_start)) }} -
                                                    {{ date('h:i:sa ', strtotime($item->time_end)) }}

                                                    <div style="color:red"> Kuota : {{ $item->kuota }} /org</div>

                                                    <span style="font-size: 10px">*Syarat dan Ketentuan Berlaku</span>

                                                </div>
                                                <div class="sc_price_block_link">
                                                    <a href="{{ route('daftar.show', $item->id) }}"
                                                        class="sc_button sc_button_square sc_button_style_filled sc_button_size_large">
                                                        <span class="cube flip-to-top">
                                                            <span class="default-state">
                                                                <span>Lihat Detail</span>
                                                            </span>
                                                            <span class="active-state">
                                                                <span>Lihat Detail</span>
                                                            </span>
                                                        </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                    <!-- /Price Block -->
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <!-- /Content -->
        </div>
    </div>
    <!-- Price Block -->
@endsection


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
</script>

resources/views/frontend/pages/pengaduan.blade.php
@extends('frontend.layouts.main')


@section('content')
    <!-- Page Content Wrap -->
    <div class="page_content_wrap page_paddings_no">
        <!-- Contact form  -->
        <div class="content contact_form_custom_1">
            <div class="sc_content content_wrap margin_top_null margin_bottom_null">
                <h3
                    class="sc_title sc_title_underline sc_align_center margin_top_null margin_bottom_null text_align_center color_white font_size_3_571em">
                    Contact Us Today</h3>
                <div id="sc_form_1_wrap" class="sc_form_wrap">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="display: none;"
                        style="color: red">
                    </div>
                    <div id="sc_form_1" class="sc_form sc_form_style_form_1 aligncenter width_66_per">
                        <form id="aduanForm" method="post">
                            <div class="sc_form_info">
                                <div class="sc_form_item sc_form_field label_over">
                                    <label class="required" for="name">Name</label>
                                    <input id="name" type="text" name="name" placeholder="Name *"
                                        value="{{ Auth::user()->name }}" disabled>
                                    <input id="user_id" type="hidden" name="user_id" placeholder="Name *"
                                        value="{{ Auth::user()->id }}" disabled>
                                </div>
                                <div class="sc_form_item sc_form_field label_over">
                                    <label class="required" for="email">E-mail</label>
                                    <input id="email" type="text" name="email" placeholder="E-mail"
                                        value="{{ Auth::user()->email }}" disabled>
                                </div>
                                <div class="sc_form_item sc_form_field label_over">
                                    <label class="required" for="subjek">Subject Aduan</label>
                                    <input id="subjek" type="text" name="subject" placeholder="Subject">
                                </div>
                            </div>
                            <div class="sc_form_item sc_form_message label_over">
                                <label class="required" for="deskripsi">Deskripsi Aduan</label>
                                <textarea id="deskripsi" name="deskripsi" placeholder="Deskripsi Aduan"></textarea>
                            </div>
                            <div class="sc_form_item sc_form_button">
                                <button name="sendBtn" id="sendBtn" value="create">Send Message</button>
                            </div>
                            <div class="result sc_infobox"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Contact form  -->
        <!-- Google map -->
        <div class="content">
            <div class="sc_section">
                <div class="sc_section_inner">
                    <div id="sc_googlemap_1" class="sc_googlemap width_100_per height_400" data-zoom="10"
                        data-style="custom">
                        <div id="sc_googlemap_1_1" class="sc_googlemap_marker" data-title="U.S. Bank"
                            data-description="&lt;p&gt;&lt;strong&gt;U.S. Bank&lt;/strong&gt;&lt;br /&gt; A reliable bank with ancient traditions and friendly staff&lt;/p&gt;"
                            data-address="5611 West Madison Street, Chicago, IL 60644" data-latlng=""
                            data-point="images/marker.png"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Google map -->
    </div>
    <!-- /Page Content Wrap -->
@endsection


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
    crossorigin="anonymous"></script>


<script>
    $(document).ready(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#sendBtn').click(function(e) {
            e.preventDefault();
            $(this).html('Sending..');
            var formData = new FormData();
            formData.append('user_id', $("#user_id").val());
            formData.append('subjek', $("#subjek").val());
            formData.append('deskripsi', $("#deskripsi").val());

            $.ajax({
                url: "{{ route('aduan.store') }}",
                data: formData,
                type: "POST",
                processData: false,
                contentType: false,
                cache: false,

                success: function(response) {
                    console.log(response)
                    if (response.errors) {
                        $('#update-profile').html('Store Transaction');
                        $('.btn-warning').html('');
                        $.each(response.errors, function(key, value) {
                            $('.alert-danger').show();
                            $('.alert-danger').append('<strong><li>' + value +
                                '</li></strong>');
                        });
                        $('#sendBtn').html('SIMPAN');
                    } else {
                        swal({
                            type: 'success',
                            icon: 'success',
                            title: `${response.message}`,
                            showConfirmButton: false,
                            timer: 3000
                        });
                        $('#sendBtn').html('SIMPAN');
                        window.location = '{{ url('/aduanSukses') }}'
                    }
                }
            });
        });

    });
</script>