routes/web.php
<?php

use App\Http\Controllers\Backend\DataPaketLatihanController;
use App\Http\Controllers\Backend\DataPelatihController;
use App\Http\Controllers\Backend\DataPengaduanController;
use App\Http\Controllers\Backend\PelangganController;
use App\Http\Controllers\Backend\TransaksiController;
use App\Http\Controllers\Frontend\AduanControllerr;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\DaftarController;
use App\Http\Controllers\Frontend\PelatihController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Models\DataPelatih;
use App\Models\DataPengaduan;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('frontend.dashboard');
})->name('homepage');

Route::group(['middleware' => ['role:admin', 'auth']], function () {

    // Dashboard
    Route::get('/dashboard', function () {
        $paket = PaketLatihan::count();
        $aduan = DataPengaduan::count();
        $transaksi = Transaksi::count();
        $pelatih = DataPelatih::count();
        $user = User::where('level', 'pelanggan')->count();
        return view('backend.dashboard', compact('paket', 'aduan', 'transaksi', 'user', 'pelatih'));
    })->name('dashboard');

    // Data Pelanggan
    Route::resource('pelanggan', PelangganController::class);

    // Data Pelatih
    Route::resource('dataPelatih', DataPelatihController::class);
    Route::get('/getDataPelatih', DataPelatihController::class . '@getDataPelatih');

    // Data Paket Latihan
    Route::resource('paket', DataPaketLatihanController::class);

    // Data Pengaduan
    Route::resource('pengaduan', DataPengaduanController::class);

    // Data Transaksi
    Route::resource('transaksi', TransaksiController::class);
    Route::get('/history', TransaksiController::class . '@history')->name('history.index');
});

Route::resource('daftar', DaftarController::class);
Route::resource('profile', ProfileController::class);
Route::resource('pelatih', PelatihController::class);

Route::get('/jadwal', DaftarController::class . '@getJadwal')->name('jadwal.index');

Route::get('/tutorial', function () {
    return view('frontend.pages.tutorial');
})->name('tutorial.index');

Route::group(['middleware' => ['role:user', 'auth']], function () {
    Route::resource('aduan', AduanControllerr::class);
    Route::get('/aduanSukses', AduanControllerr::class . '@aduanSuccess')->name('aduan.success');
    Route::get('/checkout/{id}', CheckoutController::class . '@checkout')->name('checkout');
    Route::post('/order', CheckoutController::class . '@store')->name('store.transaction');
    Route::get('/orderSukses', CheckoutController::class . '@orderSuccess')->name('order.success');
});


Route::get('/coba', function () {
    return PaketLatihan::with(['detail'])->where('id', 1)->where('status', 'aktif')->get();
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Backend/DataPaketLatihanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BiodataPelatih;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class DataPaketLatihanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $pakets = PaketLatihan::latest()->get();
            return DataTables::of($pakets)
                ->addIndexColumn()
                ->addColumn('nama_paket', function ($paket) {
                    return (ucfirst($paket->nama_paket));
                })
                ->addColumn('harga', function ($paket) {
                    return ('Rp. ' . number_format($paket->harga));
                })
                ->addColumn('durasi', function ($paket) {
                    return ($paket->durasi . ' Jam');
                })
                ->addColumn('status', function ($paket) {
                    if ($paket->status == 'aktif') {
                        return '<div class="btn btn-primary">' . ucfirst($paket->status) . '</div>';
                    } else {
                        return '<div class="btn btn-danger">' . ucfirst($paket->status) . '</div>';
                    }
                })
                ->addColumn('action', function ($paket) {

                    if ($paket->status == 'aktif') {
                        $button = '<i class="fa fa-times"></i>';
                        $class = 'danger';
                        $title = 'Arsip';
                    } else {
                        $title = 'Aktifkan';
                        $class = 'success';
                        $button = '<i class="fa fa-undo"></i>';
                    }

                    $btn = '<button href="booking/' . $paket->id . '" id="edit-paket" data-id="' . $paket->id . '" title="Edit" class="btn btn-default edit-paket"><i class="fa fa-pencil"></i></button>';


                    $btn = $btn . ' <button id="delete-paket" data-id="' . $paket->id . '" class="btn btn-' . $class . ' btn-md" title="' . $title . '">' . $button . '</button>';

                    $btn = $btn . ' <button id="show-paket" data-id="' . $paket->id . '" class="btn btn-primary btn-md" title="Show"><i class="fa fa-eye"></i></button>';

                    return $btn;
                })
                ->rawColumns(['status', 'action'])
                ->make(true);
        }

        return view('backend.data-master.data-paket');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'nama_paket' => 'required',
            'jml_pelatih' => 'required',
            'jml_asisten' => 'required',
            'jml_ballboy' => 'required',
            'tgl_start' => 'required',
            'tgl_end' => 'required',
            'time_start' => 'required',
            'time_end' => 'required',
            'kuota' => 'required',
            'harga' => 'required',
            'durasi' => 'required',
            'nama_pelatih1' => 'required',
            'nama_asisten1' => 'required',
            'nama_ballboy1' => 'required',
            'materi' => 'required',
            'peralatan' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $user = PaketLatihan::updateOrCreate([
            'id' => $request->id
        ], [
            'nama_paket' => $request->nama_paket,
            'jml_pelatih' => $request->jml_pelatih,
            'jml_asisten' => $request->jml_asisten,
            'jml_ballboy' => $request->jml_ballboy,
            'tgl_start' => $request->tgl_start,
            'tgl_end' => $request->tgl_end,
            'time_start' => $request->time_start,
            'time_end' => $request->time_end,
            'durasi' => $request->durasi,
            'harga' => $request->harga,
            'kuota' => $request->kuota,
        ]);

        $detail = BiodataPelatih::updateOrCreate(
            [
                'id' => $request->id
            ],
            [
                'nama_pelatih1' => $request->nama_pelatih1,
                'nama_pelatih2' => $request->nama_pelatih2,
                'nama_pelatih3' => $request->nama_pelatih3,
                'nama_asisten1' => $request->nama_asisten1,
                'nama_asisten2' => $request->nama_asisten2,
                'nama_asisten3' => $request->nama_asisten3,
                'nama_ballboy1' => $request->nama_ballboy1,
                'nama_ballboy2' => $request->nama_ballboy2,
                'nama_ballboy3' => $request->nama_ballboy3,
                'materi' => $request->materi,
                'peralatan' => $request->peralatan,
                'paket_id' => $user->id
            ]
        );

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $paketLatihan = PaketLatihan::with(['detail'])->where('id', $id)->first();
        return response()->json($paketLatihan);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $paket = PaketLatihan::find($id);
        if ($paket->status == 'aktif') {
            $paket->update([
                'status' => 'non-aktif'
            ]);
            return response()->json(['status' => 'Berhasil Mengarsipkan Data!']);
        } else {
            $paket->update([
                'status' => 'aktif'
            ]);
            return response()->json(['status' => 'Berhasil Menampilkan Data!']);
        }
    }
}

app/Http/Controllers/Backend/DataPelatihController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\DataPelatih;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class DataPelatihController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $pelatihs = DataPelatih::latest()->get();
            return DataTables::of($pelatihs)
                ->addIndexColumn()
                ->addColumn('nama_pelatih', function ($pelatih) {
                    return strtoupper($pelatih->nama_pelatih);
                })
                ->addColumn('pengalaman', function ($pelatih) {
                    return ucfirst($pelatih->pengalaman);
                })
                ->addColumn('img_pelatih', function ($pelatih) {
                    $url = asset('storage/uploads/img/' . $pelatih->img_pelatih);
                    if ($pelatih->img_pelatih == null) {
                    } else {
                        return '<img src="' . $url . '" width="80px" class="img-rounded" align="center" />';
                    }
                })
                ->addColumn('status', function ($pelatih) {
                    if ($pelatih->status == 'aktif') {
                        return '<div class="btn btn-primary">' . ucfirst($pelatih->status) . '</div>';
                    } else {
                        return '<div class="btn btn-danger">' . ucfirst($pelatih->status) . '</div>';
                    }
                })
                ->addColumn('action', function ($pelatih) {

                    if ($pelatih->status == 'aktif') {
                        $button = '<i class="fa fa-times"></i>';
                        $class = 'danger';
                        $title = 'Arsip';
                    } else {
                        $title = 'Aktifkan';
                        $class = 'success';
                        $button = '<i class="fa fa-undo"></i>';
                    }

                    $btn = '<button id="edit-pelatih" data-id="' . $pelatih->id . '" title="Edit" class="btn btn-default edit-pelatih"><i class="fa fa-pencil"></i></button>';


                    $btn = $btn . ' <button id="delete-pelatih" data-id="' . $pelatih->id . '" class="btn btn-' . $class . ' btn-md" title="' . $title . '">' . $button . '</button>';

                    return $btn;
                })
                ->rawColumns(['img_pelatih', 'status', 'action'])
                ->make(true);
        }

        return view('backend.data-master.data-pelatih');
    }

    public function getDataPelatih()
    {
        $data = DataPelatih::all();
        return response()->json([
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Request $request)
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'nama_pelatih' => 'required',
            'pengalaman' => 'required',
            // 'img_pelatih' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        // return response()->json($request->all());

        if ($image = $request->file('img_pelatih')) {

            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('uploads/img/', $fileName, 'public');
            $nama_pelatih = $request->input('nama_pelatih');
            $pengalaman = $request->input('pengalaman');

            // Store Data or Update Data
            $user = DataPelatih::updateOrCreate([
                'id' => $request->input('pelatih_id'),
            ], [
                'nama_pelatih' => $nama_pelatih,
                'pengalaman' => $pengalaman,
                'img_pelatih' => $fileName
            ]);
        } else {

            $nama_pelatih = $request->input('nama_pelatih');
            $pengalaman = $request->input('pengalaman');

            // Store Data or Update Data
            $user = DataPelatih::updateOrCreate([
                'id' => $request->input('pelatih_id'),
            ], [
                'nama_pelatih' => $nama_pelatih,
                'pengalaman' => $pengalaman,
            ]);
        }

        // if ($request->hasFile('img_pelatih')) {

        //     $file = $request->file('img_pelatih');
        //     $extension = $file->getClientOriginalExtension();
        //     $filename = time() . '-' . $extension;
        //     $file->move('uploads/img/', $filename);
        // }

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $dataPelatih = DataPelatih::find($id);
        return response()->json($dataPelatih);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = DataPelatih::find($id);
        if ($user->status == 'aktif') {
            $user->update([
                'status' => 'non-aktif'
            ]);
            return response()->json(['status' => 'Berhasil Mengarsipkan Data!']);
        } else {
            $user->update([
                'status' => 'aktif'
            ]);
            return response()->json(['status' => 'Berhasil Menampilkan Data!']);
        }
    }
}

resources/views/backend/layouts/header-dashboard.blade.php
    <!-- Dashboard Header -->
    <!-- For an image header add the class 'content-header-media' and an image as in the following example -->
    <div class="content-header content-header-media">
        <div class="header-section">
            <div class="row">
                <!-- Main Title (hidden on small devices for the statistics to fit) -->
                <div class="col-md-4 col-lg-6 hidden-xs hidden-sm">
                    <h1>Welcome <strong>{{ ucfirst(Auth::user()->name) }}</strong><br><small>You Look Awesome!</small>
                    </h1>

                </div>
                <!-- END Main Title -->
            </div>
        </div>
        <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
        <img src="{{ asset('backend/img/placeholders/headers/dashboard_header.jpg') }}" alt="header image"
            class="animation-pulseSlow">
    </div>

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar -->
<div id="sidebar">
    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Brand -->
            <a href="index.html" class="sidebar-brand">
                <i class="gi gi-flash"></i><span class="sidebar-nav-mini-hide"><strong>Trainer</strong>Tennis</span>
            </a>
            <!-- END Brand -->

            <!-- User Info -->
            <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
                <div class="sidebar-user-avatar">
                    <a href="page_ready_user_profile.html">
                        <img src="{{ asset('backend/img/placeholders/avatars/avatar2.jpg') }}" alt="avatar">
                    </a>
                </div>
                <div class="sidebar-user-name">{{ ucfirst(Auth::user()->name) }}</div>
                <div class="sidebar-user-links">
                    <a href="page_ready_user_profile.html" data-toggle="tooltip" data-placement="bottom"
                        title="Profile"><i class="gi gi-user"></i></a>
                    <a href="page_ready_inbox.html" data-toggle="tooltip" data-placement="bottom" title="Messages"><i
                            class="gi gi-envelope"></i></a>
                    <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
                    <a href="javascript:void(0)" class="enable-tooltip" data-placement="bottom" title="Settings"
                        onclick="$('#modal-user-settings').modal('show');"><i class="gi gi-cogwheel"></i></a>
                </div>
            </div>
            <!-- END User Info -->

            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a href="{{ route('dashboard') }}" class="{{ request()->segment(1) == 'dashboard' ? 'active' : '' }}"><i class="gi gi-stopwatch sidebar-nav-icon"></i><span
                            class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                {{-- <li>
                    <a href="#" class="sidebar-nav-menu"><i
                            class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i
                            class="gi gi-shopping_cart sidebar-nav-icon"></i><span
                            class="sidebar-nav-mini-hide">eCommerce</span></a>
                    <ul>
                        <li>
                            <a href="page_ecom_dashboard.html">Dashboard</a>
                        </li>
                        <li>
                            <a href="page_ecom_orders.html">Orders</a>
                        </li>
                        <li>
                            <a href="page_ecom_order_view.html">Order View</a>
                        </li>
                        <li>
                            <a href="page_ecom_products.html">Products</a>
                        </li>
                        <li>
                            <a href="page_ecom_product_edit.html">Product Edit</a>
                        </li>
                        <li>
                            <a href="page_ecom_customer_view.html">Customer View</a>
                        </li>
                    </ul>
                </li> --}}
                <li class="sidebar-header">
                    <span class="sidebar-header-title">Data Master</span>
                </li>

                <li class="{{ request()->segment(1) == 'pelanggan' || 'dataPelatih' || 'paket' || 'pengaduan' ? 'active' : '' }}">
                    <a href="#" class="sidebar-nav-menu"><i
                            class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i
                            class="gi gi-certificate sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Data
                            Master</span></a>
                    <ul>
                        <li>
                            <a href="pelanggan" class="{{ request()->segment(1) == 'pelanggan' ? 'active' : '' }}">Data Pelanggan</a>
                        </li>
                        <li>
                            <a href="paket" class="{{ request()->segment(1) == 'paket' ? 'active' : '' }}">Data Paket Latihan</a>
                        </li>
                        <li>
                            <a href="pengaduan" class="{{ request()->segment(1) == 'pengaduan' ? 'active' : '' }}">Data Pengaduan</a>
                        </li>
                        <li>
                            <a href="dataPelatih" class="{{ request()->segment(1) == 'dataPelatih' ? 'active' : '' }}">Data Pelatih</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-header">
                    <span class="sidebar-header-title">Data Transaksi</span>
                </li>
                <li>
                    <a href="{{ route('transaksi.index') }}" class="{{ request()->segment(1) == 'transaksi' ? 'active' : '' }}"><i class="gi gi-share_alt sidebar-nav-icon"></i><span
                            class="sidebar-nav-mini-hide">Transaksi</span></a>
                </li>
                <li>
                    <a href="{{ route('history.index') }}" class="{{ request()->segment(1) == 'history' ? 'active' : '' }}"><i class="gi gi-repeat sidebar-nav-icon"></i><span
                            class="sidebar-nav-mini-hide">History Transaksi</span></a>
                </li>
            </ul>
            <!-- END Sidebar Navigation -->
        </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->
</div>
<!-- END Main Sidebar -->