routes/web.php
<?php

use App\Http\Controllers\Backend\DataPaketLatihanController;
use App\Http\Controllers\Backend\DataPelatihController;
use App\Http\Controllers\Backend\DataPengaduanController;
use App\Http\Controllers\Backend\PelangganController;
use App\Http\Controllers\Backend\TransaksiController;
use App\Http\Controllers\Frontend\AduanControllerr;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\DaftarController;
use App\Http\Controllers\Frontend\PelatihController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Models\DataPelatih;
use App\Models\DataPengaduan;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('frontend.dashboard');
})->name('homepage');

Route::group(['middleware' => ['role:admin', 'auth']], function () {

    // Dashboard
    Route::get('/dashboard', function () {
        $paket = PaketLatihan::count();
        $aduan = DataPengaduan::count();
        $transaksi = Transaksi::count();
        $pelatih = DataPelatih::count();
        $user = User::where('level', 'pelanggan')->count();
        return view('backend.dashboard', compact('paket', 'aduan', 'transaksi', 'user', 'pelatih'));
    })->name('dashboard');

    // Data Pelanggan
    Route::resource('pelanggan', PelangganController::class);

    // Data Pelatih
    Route::resource('dataPelatih', DataPelatihController::class);
    Route::get('/getDataPelatih', DataPelatihController::class . '@getDataPelatih');

    // Data Paket Latihan
    Route::resource('paket', DataPaketLatihanController::class);

    // Data Pengaduan
    Route::resource('pengaduan', DataPengaduanController::class);

    // Data Transaksi
    Route::resource('transaksi', TransaksiController::class);
    Route::get('/history', TransaksiController::class . '@history')->name('history.index');
});

Route::resource('daftar', DaftarController::class);
Route::resource('profile', ProfileController::class);
Route::resource('pelatih', PelatihController::class);

Route::get('/jadwal', DaftarController::class . '@getJadwal')->name('jadwal.index');

Route::get('/tutorial', function () {
    return view('frontend.pages.tutorial');
})->name('tutorial.index');

Route::group(['middleware' => ['role:user', 'auth']], function () {
    Route::resource('aduan', AduanControllerr::class);
    Route::get('/aduanSukses', AduanControllerr::class . '@aduanSuccess')->name('aduan.success');
    Route::get('/checkout/{id}', CheckoutController::class . '@checkout')->name('checkout');
    Route::post('/order', CheckoutController::class . '@store')->name('store.transaction');
    Route::get('/orderSukses', CheckoutController::class . '@orderSuccess')->name('order.success');
});


Route::get('/coba', function () {
    return PaketLatihan::with(['detail'])->where('id', 1)->where('status', 'aktif')->get();
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Backend/DataPaketLatihanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BiodataPelatih;
use App\Models\PaketLatihan;
use App\Models\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class DataPaketLatihanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $pakets = PaketLatihan::latest()->get();
            return DataTables::of($pakets)
                ->addIndexColumn()
                ->addColumn('nama_paket', function ($paket) {
                    return (ucfirst($paket->nama_paket));
                })
                ->addColumn('harga', function ($paket) {
                    return ('Rp. ' . number_format($paket->harga));
                })
                ->addColumn('durasi', function ($paket) {
                    return ($paket->durasi . ' Jam');
                })
                ->addColumn('status', function ($paket) {
                    if ($paket->status == 'aktif') {
                        return '<div class="btn btn-primary">' . ucfirst($paket->status) . '</div>';
                    } else {
                        return '<div class="btn btn-danger">' . ucfirst($paket->status) . '</div>';
                    }
                })
                ->addColumn('action', function ($paket) {

                    if ($paket->status == 'aktif') {
                        $button = '<i class="fa fa-times"></i>';
                        $class = 'danger';
                        $title = 'Arsip';
                    } else {
                        $title = 'Aktifkan';
                        $class = 'success';
                        $button = '<i class="fa fa-undo"></i>';
                    }

                    $btn = '<button href="booking/' . $paket->id . '" id="edit-paket" data-id="' . $paket->id . '" title="Edit" class="btn btn-default edit-paket"><i class="fa fa-pencil"></i></button>';


                    $btn = $btn . ' <button id="delete-paket" data-id="' . $paket->id . '" class="btn btn-' . $class . ' btn-md" title="' . $title . '">' . $button . '</button>';

                    $btn = $btn . ' <button id="show-paket" data-id="' . $paket->id . '" class="btn btn-primary btn-md" title="Show"><i class="fa fa-eye"></i></button>';

                    return $btn;
                })
                ->rawColumns(['status', 'action'])
                ->make(true);
        }

        return view('backend.data-master.data-paket');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'nama_paket' => 'required',
            'jml_pelatih' => 'required',
            'jml_asisten' => 'required',
            'jml_ballboy' => 'required',
            'tgl_start' => 'required',
            'tgl_end' => 'required',
            'time_start' => 'required',
            'time_end' => 'required',
            'kuota' => 'required',
            'harga' => 'required',
            'durasi' => 'required',
            'nama_pelatih1' => 'required',
            'nama_asisten1' => 'required',
            'nama_ballboy1' => 'required',
            'materi' => 'required',
            'peralatan' => 'required',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        $user = PaketLatihan::updateOrCreate([
            'id' => $request->id
        ], [
            'nama_paket' => $request->nama_paket,
            'jml_pelatih' => $request->jml_pelatih,
            'jml_asisten' => $request->jml_asisten,
            'jml_ballboy' => $request->jml_ballboy,
            'tgl_start' => $request->tgl_start,
            'tgl_end' => $request->tgl_end,
            'time_start' => $request->time_start,
            'time_end' => $request->time_end,
            'durasi' => $request->durasi,
            'harga' => $request->harga,
            'kuota' => $request->kuota,
        ]);

        $detail = BiodataPelatih::updateOrCreate(
            [
                'id' => $request->id
            ],
            [
                'nama_pelatih1' => $request->nama_pelatih1,
                'nama_pelatih2' => $request->nama_pelatih2,
                'nama_pelatih3' => $request->nama_pelatih3,
                'nama_asisten1' => $request->nama_asisten1,
                'nama_asisten2' => $request->nama_asisten2,
                'nama_asisten3' => $request->nama_asisten3,
                'nama_ballboy1' => $request->nama_ballboy1,
                'nama_ballboy2' => $request->nama_ballboy2,
                'nama_ballboy3' => $request->nama_ballboy3,
                'materi' => $request->materi,
                'peralatan' => $request->peralatan,
                'paket_id' => $user->id
            ]
        );

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $paketLatihan = PaketLatihan::with(['detail'])->where('id', $id)->first();
        return response()->json($paketLatihan);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $paket = PaketLatihan::find($id);
        if ($paket->status == 'aktif') {
            $paket->update([
                'status' => 'non-aktif'
            ]);
            return response()->json(['status' => 'Berhasil Mengarsipkan Data!']);
        } else {
            $paket->update([
                'status' => 'aktif'
            ]);
            return response()->json(['status' => 'Berhasil Menampilkan Data!']);
        }
    }
}

app/Http/Controllers/Backend/DataPelatihController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\DataPelatih;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class DataPelatihController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $pelatihs = DataPelatih::latest()->get();
            return DataTables::of($pelatihs)
                ->addIndexColumn()
                ->addColumn('nama_pelatih', function ($pelatih) {
                    return strtoupper($pelatih->nama_pelatih);
                })
                ->addColumn('pengalaman', function ($pelatih) {
                    return ucfirst($pelatih->pengalaman);
                })
                ->addColumn('img_pelatih', function ($pelatih) {
                    $url = asset('storage/uploads/img/' . $pelatih->img_pelatih);
                    if ($pelatih->img_pelatih == null) {
                    } else {
                        return '<img src="' . $url . '" width="80px" class="img-rounded" align="center" />';
                    }
                })
                ->addColumn('status', function ($pelatih) {
                    if ($pelatih->status == 'aktif') {
                        return '<div class="btn btn-primary">' . ucfirst($pelatih->status) . '</div>';
                    } else {
                        return '<div class="btn btn-danger">' . ucfirst($pelatih->status) . '</div>';
                    }
                })
                ->addColumn('action', function ($pelatih) {

                    if ($pelatih->status == 'aktif') {
                        $button = '<i class="fa fa-times"></i>';
                        $class = 'danger';
                        $title = 'Arsip';
                    } else {
                        $title = 'Aktifkan';
                        $class = 'success';
                        $button = '<i class="fa fa-undo"></i>';
                    }

                    $btn = '<button id="edit-pelatih" data-id="' . $pelatih->id . '" title="Edit" class="btn btn-default edit-pelatih"><i class="fa fa-pencil"></i></button>';


                    $btn = $btn . ' <button id="delete-pelatih" data-id="' . $pelatih->id . '" class="btn btn-' . $class . ' btn-md" title="' . $title . '">' . $button . '</button>';

                    return $btn;
                })
                ->rawColumns(['img_pelatih', 'status', 'action'])
                ->make(true);
        }

        return view('backend.data-master.data-pelatih');
    }

    public function getDataPelatih()
    {
        $data = DataPelatih::all();
        return response()->json([
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Request $request)
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //define validation rules
        $validator = Validator::make($request->all(), [
            'nama_pelatih' => 'required',
            'pengalaman' => 'required',
            // 'img_pelatih' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        //check if validation fails
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->all()]);
        }

        // return response()->json($request->all());

        if ($image = $request->file('img_pelatih')) {

            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('uploads/img/', $fileName, 'public');
            $nama_pelatih = $request->input('nama_pelatih');
            $pengalaman = $request->input('pengalaman');

            // Store Data or Update Data
            $user = DataPelatih::updateOrCreate([
                'id' => $request->input('pelatih_id'),
            ], [
                'nama_pelatih' => $nama_pelatih,
                'pengalaman' => $pengalaman,
                'img_pelatih' => $fileName
            ]);
        } else {

            $nama_pelatih = $request->input('nama_pelatih');
            $pengalaman = $request->input('pengalaman');

            // Store Data or Update Data
            $user = DataPelatih::updateOrCreate([
                'id' => $request->input('pelatih_id'),
            ], [
                'nama_pelatih' => $nama_pelatih,
                'pengalaman' => $pengalaman,
            ]);
        }

        // if ($request->hasFile('img_pelatih')) {

        //     $file = $request->file('img_pelatih');
        //     $extension = $file->getClientOriginalExtension();
        //     $filename = time() . '-' . $extension;
        //     $file->move('uploads/img/', $filename);
        // }

        //return response
        return response()->json([
            'success' => true,
            'message' => 'Data Berhasil Disimpan!',
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $dataPelatih = DataPelatih::find($id);
        return response()->json($dataPelatih);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = DataPelatih::find($id);
        if ($user->status == 'aktif') {
            $user->update([
                'status' => 'non-aktif'
            ]);
            return response()->json(['status' => 'Berhasil Mengarsipkan Data!']);
        } else {
            $user->update([
                'status' => 'aktif'
            ]);
            return response()->json(['status' => 'Berhasil Menampilkan Data!']);
        }
    }
}

resources/views/backend/data-master/data-pelanggan.blade.php
@extends('backend.main')

@section('content')
    <!-- Page content -->
    <div id="page-content">
        <!-- Datatables Header -->
        <div class="content-header">
            <div class="header-section">
                <h1>
                    <i class="fa fa-table"></i>Master Data<br><small>Data Pelanggan</small>
                </h1>
            </div>
        </div>
        <ul class="breadcrumb breadcrumb-top">
            <li>Master Data</li>
            <li><a href="">Data Pelanggan</a></li>
        </ul>
        <!-- END Datatables Header -->

        <!-- Datatables Content -->
        <div class="block full">
            <div class="block-title">
                <h2><strong>Data</strong> Pelanggan</h2>
            </div>
            {{-- <div>
                <div class="col">
                    <button style="margin-bottom:10px" type="button" class="btn btn-info btn-sm mt-2" data-toggle="modal"
                        data-target="#modal-create" id="btn-create-user"><i class="fa fa-plus"></i>
                        Tambah
                        Data</button>
                </div>
            </div> --}}

            <div class="table-responsive">
                <table id="example-datatable" class="table datatable table-center table-condensed table-bordered"
                    width="100%">
                    <thead>
                        <tr>
                            <th class="text-center">No</th>
                            <th>Nama Pelanggan</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END Datatables Content -->
    </div>
    <!-- END Page Content -->
@endsection

<!-- Modal -->
<div class="modal fade" id="ajaxModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modelHeading"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="btn-warning" style="font-color:red;" role="alert" style="display: none;"></div>
                <form id="userForm" name="userForm" class="form-bordered">
                    <input type="hidden" class="user_id" name="user_id" id="user_id">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control"
                            placeholder="Enter name..">
                        <span class="help-block">Please enter your name</span>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control"
                            placeholder="Enter Email..">
                        <span class="help-block">Please enter your email</span>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control"
                            placeholder="Enter Password..">
                        <span class="help-block">Please enter your password</span>
                    </div>
                    <div class="form-group">
                        <label for="password">Confirmation Password</label>
                        <input type="password" id="password_confirmation" name="password_confirmation"
                            class="form-control" placeholder="Enter password again..">
                        <span class="help-block">Please enter your password again</span>
                    </div>
                    <div class="form-group form-actions">
                        <button type="submit" class="btn btn-sm btn-primary" id="saveBtn" value="create"><i
                                class="fa fa-user"></i>
                            Save</button>
                        <button type="reset" class="btn btn-sm btn-secondary" data-dismiss="modal"><i
                                class="fa fa-power-off"></i>
                            Close</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="btn-info" style="margin-left: 10px " role="alert" style="display: none;"></div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>

@push('script-alt')
    {{-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script> --}}
    {{-- <script type="text/javascript" src="https://cdn.datatables.net/1.13.3/js/dataTables.bootstrap4.min.js"></script> --}}
    {{-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script> --}}
    {{-- <script type="text/javascript" src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script> --}}
    <script src="{{ asset('backend/js/pages/tablesDatatables.js') }}"></script>
@endpush

<script>
    $(document).ready(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        // Rendering Table
        var table = $('.datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('pelanggan.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'status',
                    name: 'status'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                },
            ]
        });

        // Create New Pelanggan.
        $('#btn-create-user').click(function() {
            $('#saveBtn').val("create-user");
            $('#user_id').val('');
            $('#userForm').trigger("reset");
            $('#modelHeading').html("TAMBAH DATA SUPPLIER BARU");
            $('#ajaxModel').modal('show');
        });

        $('#saveBtn').click(function(e) {
            e.preventDefault();
            $(this).html('Sending..');
            var formData = $('#userForm').serialize();

            $.ajax({
                url: "{{ route('pelanggan.store') }}",
                // method: 'post',
                data: {
                    id: $('#user_id').val(),
                    name: $('#name').val(),
                    email: $('#email').val(),
                    password: $('#password').val(),
                    password_confirmation: $('#password_confirmation').val()
                },
                // data: $('#supplierForm').serialize(),
                type: "POST",
                dataType: 'json',

                success: function(response) {
                    console.log(response)
                    if (response.errors) {
                        $('.btn-warning').html('');
                        $.each(response.errors, function(key, value) {
                            $('.btn-warning').show();
                            $('.btn-warning').append(
                                '<li>' + value +
                                '</li>');
                        });
                        $('#saveBtn').html('SIMPAN');

                    } else {
                        $('.btn-warning').hide();

                        swal({
                            type: 'success',
                            icon: 'success',
                            title: `${response.message}`,
                            showConfirmButton: false,
                            timer: 3000
                        });

                        $('#userForm').trigger("reset");
                        $('#saveBtn').html('SIMPAN');
                        $('#ajaxModel').modal('hide');

                        table.draw();
                    }
                }
            });
        });

        // Edit Data Pelanggan
        $('body').on('click', '.edit-user', function() {
            var user_id = $(this).data('id');
            $.get("{{ route('pelanggan.index') }}" + '/' + user_id + '/edit', function(
                data) {
                $('#modelHeading').html("EDIT DATA PELANGGAN");
                $('#saveBtn').val("edit-user");
                $('#ajaxModel').modal('show');
                $('#user_id').val(data.id);
                $('#name').val(data.name);
                $('#email').val(data.email);
            })
        });

        // Arsipkan Data
        $('body').on('click', '#delete-user', function() {

            swal({
                    title: "Apakah anda yakin?",
                    text: "Setelah diNon-Aktifkan, User Tidak Bisa Melakukan Transaksi Lagi!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })

                .then((willDelete) => {
                    if (willDelete) {
                        var user_id = $(this).data("id");
                        $.ajax({
                            type: "DELETE",
                            url: 'pelanggan/' + user_id,
                            data: user_id,
                            success: function(response) {
                                swal(response.status, {
                                        icon: "success",
                                    })
                                    .then((result) => {
                                        table.draw();
                                    });
                            }
                        });
                    } else {
                        swal("Cancel!", "Perintah dibatalkan!", "error");

                    }
                });
        });

    });
</script>